# Markdown Lint配置文件
# 詳細說明見: https://github.com/DavidAnson/markdownlint-cli2

# 基本配置
config:
  # 預設啟用所有規則
  default: true
  
  # 自定義規則配置
  # MD013 行長度規則 - 針對中文內容放寬限制
  MD013:
    line_length: 300
    stern: false
    code_blocks: false
    tables: false
  
  # MD026 標題中的結尾標點符號 - 完全禁用，中文標題通常使用冒號
  MD026: false
  
  # MD033 禁止內嵌HTML - 由於我們使用Tailwind和自定義組件，放寬此限制
  MD033: true
  
  # MD022 標題前後的空行 - 文檔使用大量標題，在中文語境中不影響可讀性
  MD022: false
  
  # MD032 列表前後的空行 - 在中文語境中不影響可讀性
  MD032: false
  
  # 縮排規則
  MD007:
    indent: 4  # 允許4空格縮排
  
  # MD030 列表標記後的空格
  MD030:
    ul_single: 1
    ol_single: 2  # 允許有2個空格
    ul_multi: 1
    ol_multi: 2
  
  # MD012 連續空行數量限制
  MD012:
    maximum: 2
  
  # MD058 表格前後需要空行
  MD058: false
  
  # MD046 代碼塊樣式 - 關閉此檢查，允許縮進式代碼塊
  MD046: false
  
  # MD047 文件末尾需要換行符
  MD047: true
  
  # MD040 圍欄式代碼塊需要指定語言 - 關閉此檢查
  MD040: false
  
  # MD031 圍欄式代碼塊前後需要空行 - 關閉此檢查
  MD031: false

# 指定 globs 可以用來批量執行 markdownlint 檢查
globs:
  - "docs/**/*.md"
  - "src/content/**/*.md"
  - "src/pages/**/*.md"

# 忽略特定文件或目錄
ignores:
  - "node_modules/**"
  - "dist/**"
  - "public/**"
  - ".git/**"
  - ".github/**"
  - "README.md"  # 如果你想忽略 README

# 啟用 .gitignore 支持
gitignore: true

# 完成後不顯示橫幅
noBanner: false

# 在檢查過程中顯示進度
noProgress: false

# 顯示找到的文件列表
showFound: false

# 禁用內嵌配置註釋
noInlineConfig: false

# 啟用自動修復（謹慎使用）
fix: false

# 自定義規則路徑（如果有的話）
# customRules:
#   - "scripts/custom-markdown-rules.js"

# 指定輸出格式化
# outputFormatters:
#   - ["formatter-name", param1, param2] 